In [48]:
import numpy as np

In [8]:
arr = np.array([[9,8,7],[6,5,4],[1,2,3]])
for x in range(0,len(arr)):
    for y in range(0,len(arr[x])):
        print(arr[x][y],end=" ")
    print("\n")

# print(arr[0][1])

9 8 7 

6 5 4 

1 2 3 



In [4]:
arr1 = np.array([[0,1,2],[3,4,5]])
# arrsum = np.sum(arr1,axis = 1)
arrsum = np.sum(arr1,axis = 0)

print(arrsum)

[3 5 7]


In [27]:
np.zeros((4,3),dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.arange(2,10,0.75,dtype=float)

array([2.  , 2.75, 3.5 , 4.25, 5.  , 5.75, 6.5 , 7.25, 8.  , 8.75, 9.5 ])

In [40]:
np.linspace(2,10,num=10,endpoint=False,dtype=int)

array([2, 2, 3, 4, 5, 6, 6, 7, 8, 9])

## different sorting techniques in numpy
* **sort**
    * sort will sort the array 
    numpy.sort(arr, axis = -1, kind = None, order = None)
        * arr - array to be sorted
        * axis - int or none. By default its -1
        * kind - 'quicksort', 'mergesort', 'stable', 'heapsort'
        * order will sort according to the given fields
* **argsort**
    * returns an array/list of position of elements which are in sorted order
* **searchsorted**
    * numpy.searchsorted(a,v, side = 'left', sorter= None) 
        * a - input array
        * v - Values to insert into a
        * side - 'left','right' if left first index of element will be returned else last index will be returned
        * sorter - Optional array of integer indices that sort array a into ascending order. They are typically the result of argsort.
    * find indices where elements should be inserted to maintain order returns int or array of integers. Returns 0 or N if element is not found


In [35]:
# arrsort = [9,1,7,3,5]
# arrsort2d = [[9,8,7],[6,5,4],[3,2,1]]
# arrsort = np.sort(np.sort(arrsort2d), axis = 0)
# # arrsort = np.argsort(arrsort)
# print(arrsort)


dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
np.sort(a, order=['age', 'height'])                         


array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [38]:
np.searchsorted(arrsum,0)

0

In [51]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])
np.concatenate((ar1,ar2),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Determining the shape and size of an array
    *ndarray.ndim - returns the number of axes/dimensions in the array
    *ndarray.size - returns the number of elements in the array
    *ndarray.shape - returns a tuple indicating number of rows and columns in the array

In [57]:
print(ar1.ndim)
print(ar1.size)
print(ar1.shape)

2
4
(2, 2)


### reshape an array

* np.reshape(a,newshape = (),order = 'F/A/C')
    * a - array to be sorted
    * newshape = (rows,columns)
    

In [58]:
np.reshape(arr1,newshape=(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
xarr = np.arange(1,6)
xarr1 = xarr[np.newaxis, :]
xarr2 = np.expand_dims(xarr,axis = 1)
print(xarr1)
print(xarr2)
print(xarr1.shape)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
(1, 5)


In [77]:
print(xarr[-4:6])

[2 3 4 5]


In [82]:
np.flip(arr,axis = 1)

array([[7, 8, 9],
       [4, 5, 6],
       [3, 2, 1]])

In [79]:
z = arr1.flatten()
zravel = arr1.ravel()
print(z)
print(zravel)
np.array

[0 1 2 3 4 5]
[0 1 2 3 4 5]
